/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUnitsRouteImport } from './routes/_app/units'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppDashboardVisitorsRouteImport } from './routes/_app/dashboard/visitors'
import { Route as AppDashboardMessagesRouteImport } from './routes/_app/dashboard/messages'
import { Route as AppDashboardBookingsRouteImport } from './routes/_app/dashboard/bookings'
import { Route as AppAdminVisitsRouteImport } from './routes/_app/admin/visits'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminUnitsRouteImport } from './routes/_app/admin/units'
import { Route as AppAdminChatMultilangRouteImport } from './routes/_app/admin/chat-multilang'
import { Route as AppAdminChatRouteImport } from './routes/_app/admin/chat'
import { Route as AppAdminBookingsRouteImport } from './routes/_app/admin/bookings'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app/admin/analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardVisitorsRoute = AppDashboardVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardMessagesRoute = AppDashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardBookingsRoute = AppDashboardBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppAdminVisitsRoute = AppAdminVisitsRouteImport.update({
  id: '/admin/visits',
  path: '/admin/visits',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUnitsRoute = AppAdminUnitsRouteImport.update({
  id: '/admin/units',
  path: '/admin/units',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminChatMultilangRoute = AppAdminChatMultilangRouteImport.update({
  id: '/admin/chat-multilang',
  path: '/admin/chat-multilang',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminChatRoute = AppAdminChatRouteImport.update({
  id: '/admin/chat',
  path: '/admin/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBookingsRoute = AppAdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/units': typeof AppUnitsRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/bookings': typeof AppAdminBookingsRoute
  '/admin/chat': typeof AppAdminChatRoute
  '/admin/chat-multilang': typeof AppAdminChatMultilangRoute
  '/admin/units': typeof AppAdminUnitsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/visits': typeof AppAdminVisitsRoute
  '/dashboard/bookings': typeof AppDashboardBookingsRoute
  '/dashboard/messages': typeof AppDashboardMessagesRoute
  '/dashboard/visitors': typeof AppDashboardVisitorsRoute
  '/admin/': typeof AppAdminIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/units': typeof AppUnitsRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/bookings': typeof AppAdminBookingsRoute
  '/admin/chat': typeof AppAdminChatRoute
  '/admin/chat-multilang': typeof AppAdminChatMultilangRoute
  '/admin/units': typeof AppAdminUnitsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/visits': typeof AppAdminVisitsRoute
  '/dashboard/bookings': typeof AppDashboardBookingsRoute
  '/dashboard/messages': typeof AppDashboardMessagesRoute
  '/dashboard/visitors': typeof AppDashboardVisitorsRoute
  '/admin': typeof AppAdminIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/units': typeof AppUnitsRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/bookings': typeof AppAdminBookingsRoute
  '/_app/admin/chat': typeof AppAdminChatRoute
  '/_app/admin/chat-multilang': typeof AppAdminChatMultilangRoute
  '/_app/admin/units': typeof AppAdminUnitsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/visits': typeof AppAdminVisitsRoute
  '/_app/dashboard/bookings': typeof AppDashboardBookingsRoute
  '/_app/dashboard/messages': typeof AppDashboardMessagesRoute
  '/_app/dashboard/visitors': typeof AppDashboardVisitorsRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/dashboard'
    | '/units'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/chat'
    | '/admin/chat-multilang'
    | '/admin/units'
    | '/admin/users'
    | '/admin/visits'
    | '/dashboard/bookings'
    | '/dashboard/messages'
    | '/dashboard/visitors'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/units'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/chat'
    | '/admin/chat-multilang'
    | '/admin/units'
    | '/admin/users'
    | '/admin/visits'
    | '/dashboard/bookings'
    | '/dashboard/messages'
    | '/dashboard/visitors'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/register'
    | '/_app/dashboard'
    | '/_app/units'
    | '/_app/admin/analytics'
    | '/_app/admin/bookings'
    | '/_app/admin/chat'
    | '/_app/admin/chat-multilang'
    | '/_app/admin/units'
    | '/_app/admin/users'
    | '/_app/admin/visits'
    | '/_app/dashboard/bookings'
    | '/_app/dashboard/messages'
    | '/_app/dashboard/visitors'
    | '/_app/admin/'
    | '/_app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/units': {
      id: '/_app/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/visitors': {
      id: '/_app/dashboard/visitors'
      path: '/visitors'
      fullPath: '/dashboard/visitors'
      preLoaderRoute: typeof AppDashboardVisitorsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/messages': {
      id: '/_app/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AppDashboardMessagesRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/dashboard/bookings': {
      id: '/_app/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof AppDashboardBookingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/admin/visits': {
      id: '/_app/admin/visits'
      path: '/admin/visits'
      fullPath: '/admin/visits'
      preLoaderRoute: typeof AppAdminVisitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/units': {
      id: '/_app/admin/units'
      path: '/admin/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AppAdminUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/chat-multilang': {
      id: '/_app/admin/chat-multilang'
      path: '/admin/chat-multilang'
      fullPath: '/admin/chat-multilang'
      preLoaderRoute: typeof AppAdminChatMultilangRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/chat': {
      id: '/_app/admin/chat'
      path: '/admin/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AppAdminChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/bookings': {
      id: '/_app/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AppAdminBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppDashboardRouteChildren {
  AppDashboardBookingsRoute: typeof AppDashboardBookingsRoute
  AppDashboardMessagesRoute: typeof AppDashboardMessagesRoute
  AppDashboardVisitorsRoute: typeof AppDashboardVisitorsRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardBookingsRoute: AppDashboardBookingsRoute,
  AppDashboardMessagesRoute: AppDashboardMessagesRoute,
  AppDashboardVisitorsRoute: AppDashboardVisitorsRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppUnitsRoute: typeof AppUnitsRoute
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminBookingsRoute: typeof AppAdminBookingsRoute
  AppAdminChatRoute: typeof AppAdminChatRoute
  AppAdminChatMultilangRoute: typeof AppAdminChatMultilangRoute
  AppAdminUnitsRoute: typeof AppAdminUnitsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminVisitsRoute: typeof AppAdminVisitsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppUnitsRoute: AppUnitsRoute,
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminBookingsRoute: AppAdminBookingsRoute,
  AppAdminChatRoute: AppAdminChatRoute,
  AppAdminChatMultilangRoute: AppAdminChatMultilangRoute,
  AppAdminUnitsRoute: AppAdminUnitsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminVisitsRoute: AppAdminVisitsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
